### ISSUE TITLE
Shouldn't EventFacade.val() be set with params in constructor?

### ISSUE THREAD

**Issue by jesperstarkar** [johngeorgewright/hap#1]
Hi. What is the point of setting params in .fire()/.emit() unless the params gets set (or will be returned) as .val() by default? What is the idea behind this?

**Comment by johngeorgewright** [comment]
I gave the option add extra parameters to your event unrelated to the value. This may include such things as where the event originated from for example.

**Comment by jesperstarkar** [comment]
Hello, thank you for the answer.

How do you suggest I add value when firing an event then? I currently override EventFacade and create new events from it, with automatically assignment from params to .val(params).

**Comment by johngeorgewright** [comment]
You can pass your own EventFacade object instead of a params object.

https://github.com/johngeorgewright/hap/blob/master/lib/EventEmitter.js#L303

**Comment by jesperstarkar** [comment]
Yes, this is what I do.

Sorry for me being unclear, but it is in fact in the EventFacade(params) I wonder why this isn't by default returned by EventFacade.val() if you haven't set a .val(val) explicitly.

I have extended EventFacade to do just so.

**Comment by johngeorgewright** [comment]
I suppose it wouldn't be such a bad idea to be able to set the value by using a `val` property in the params object. That way it would be backwards compatible.

``` js
new EventFacade({
  prop1: prop1,
  prop2: prop2,
  val: val
});
```
